import "@/styles/globals.css";
import { Header } from '../components/header'
import localFont from 'next/font/local'
import { ViewTransitions } from 'next-view-transitions'

const sfp = localFont({
  src: [
    {
      path: '../fonts/SFProDisplay-Bold.woff2',
      weight: 'bold',
      style: 'normal',
    },
    {
      path: '../fonts/SFProDisplay-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/SFProDisplay-Regular.woff2',
      weight: 'normal',
      style: 'normal',
    },
  ],
  variable: '--font-sfp'
})


export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html className={`${sfp.variable}`}>
      <body>
          <Header />
          {children}
      </body>
    </html>
    </ViewTransitions>
  )
}